version: '3.9'

services:
  micromono-app:
    image: micromono-app:latest
    container_name: micromono-app
    ports:
      - "3002:3002"
    env_file:
      - path: config/.env.production
        required : true


