version: '3.9'

services:
  test-mono-app:
    image: test-mono-app:latest
    container_name: test-mono-app
    ports:
      - "3002:3002"
    env_file:
      - path: config/.env.production
        required : true


