version: '3.9'

services:
  eddy-am-ui-admin:
    image: am-ui-admin:latest
    container_name: am-ui-admin
    ports:
      - "3002:3002"
    env_file:
      - path: config/.env.production
        required : true


