version: '3.9'

services:
  micromono-client:
    image: micromono-client:latest
    container_name: micromono-client
    ports:
      - "3000:3000"
    env_file:
      - path: config/.env.production
        required: true


