version: '3.9'

services:
  test-mono-client:
    image: test-mono-client:latest
    container_name: test-mono-client
    ports:
      - "3000:3000"
    env_file:
      - path: config/.env.production
        required: true


