version: '3.9'

services:
  test-mono-server:
    image: test-mono-server:latest
    container_name: test-mono-server
    ports:
      - "3001:3001"
    # restart: always
    env_file:
      - path: ./config/.env.production
        required: true


