version: '3.9'

services:
  micromono-server:
    image: micromono-server:latest
    container_name: micromono-server
    ports:
      - "3001:3001"
    # restart: always
    env_file:
      - path: ./config/.env.production
        required: true


